const hypeStatements = [
    'You are [xxx] unstoppable!',
    'You can [xxx] do anything you set your mind to!',
    "Don't let anyone else's negativity [xxx] bring you down.",
    'You are in [xxx] control of your own destiny.',
    'Believe in yourself and your [xxx] abilities.',
    'You are stronger than any [xxx] challenge that comes your way.',
    'You are unique and special in your own [xxx] way.',
    "Don't let fear [xxx] hold you back from pursuing your dreams.",
    'You are [xxx] capable of achieving great things.',
    "Don't let anyone else [xxx] define your limits.",
    'The only person you need to [xxx] prove yourself to is yourself.',
    "Don't let [xxx] failure define you – learn from it and keep [xxx] pushing forward.",
    'You are worthy of [xxx] love, respect, and success.',
    "Don't let anyone else's opinions of you [xxx] bring you down.",
    'You have the [xxx] power to create the life you want for yourself.',
    'You are [xxx] worthy of all the good things in life.',
    'Your hard work and dedication will [xxx] pay off in the end.',
    'You are an important and [xxx] valuable member of your community.',
    "Don't let setbacks [xxx] hold you back – keep [xxx] pushing forward towards your goals.",
    'You have the [xxx] courage and strength to overcome any [xxx] obstacle.',
    'You are [xxx] talented and capable of achieving greatness.',
    'Your [xxx] positive attitude will help you overcome any [xxx] challenge.',
    'You are important and your [xxx] contribution to the world [xxx] matters.',
    "Believe in your own [xxx] potential and don't let anyone else [xxx] tell you otherwise.",
    'You have the [xxx] ability to make a positive impact on those around you.',
    'You are [xxx] worthy of success and happiness.',
    "Don't let anyone else's [xxx] doubt hold you back – trust in yourself and your abilities.",
    'You have the [xxx] power to create the future you want.',
    'Believe in yourself and your [xxx] abilities, and you will achieve great [xxx] things.',
    'You are [xxx] strong, capable, and deserving of all the good things in life.',
    'Your hard work and determination will [xxx] lead you to success.',
    'You have the [xxx] potential to make a difference in the world.',
    "Don't let anyone else's negativity [xxx] bring you down – stay [xxx] positive and focused on your goals.",
    'You are [xxx] unique and have something special to offer the world.',
    "Believe in yourself and don't let anyone else's [xxx] doubt hold you back.",
    'You have the [xxx] ability to overcome any [xxx] obstacle and achieve your dreams.',
    'You are [xxx] worthy of love, respect, and all the [xxx] good things in life.',
    "Don't let anyone else [xxx] define your limits – you are capable of achieving [xxx] greatness.",
    'You are a [xxx] force to be reckoned with!',
    'No [xxx] challenge is too great for you!',
    'You have the [xxx] power to achieve any [xxx] goal you set for yourself!',
    'You are [xxx] destined for greatness!',
    "Don't let anyone or anything [xxx] hold you back from reaching your full potential!",
    'You are [xxx] capable of achieving anything you put your mind to!',
    'You are [xxx] strong, powerful, and capable!',
    'You have the [xxx] determination and drive to [xxx] succeed!',
    'You are a [xxx] winner and nothing can [xxx] stand in your way!',
    'You are [xxx] brave and fearless!',
    'You are a [xxx] leader, not a follower!',
    'You have the [xxx] courage to take risks and [xxx] embrace change!',
    'You are a [xxx] trailblazer and a [xxx] trendsetter!',
    'You are [xxx] unique and special in your own [xxx] way!',
    'You are [xxx] talented and skilled in your own [xxx] right!',
    'You are [xxx] worthy of love, respect, and admiration!',
    'You are a [xxx] champion and a [xxx] winner!',
    'You are [xxx] unstoppable and unbreakable!',
    'You are an [xxx] overcomer and a [xxx] survivor!',
    'You are a [xxx] warrior and a [xxx] fighter!',
    'You are a [xxx] conqueror and a [xxx] victor!',
    'You are a [xxx] powerhouse and a [xxx] force to be reckoned with!',
    'You are a [xxx] rising star and a [xxx] shining light!',
    'You are a [xxx] hero and a [xxx] role model!',
    'You are a [xxx] visionary and a [xxx] leader!',
    'You are a [xxx] go-getter and a [xxx] doer!',
    'You are a [xxx] dreamer and a [xxx] believer!',
    'You are a [xxx] creator and an [xxx] innovator!',
    'You are a [xxx] builder and a [xxx] maker!',
    'You are a [xxx] mover and a [xxx] shaker!',
    'You are a [xxx] trailblazer and a [xxx] pioneer!',
    'You are a [xxx] game-changer and a [xxx] disruptor!',
    'You are a [xxx] master and a [xxx] pro!',
    'You are a [xxx] guru and an [xxx] expert!',
    'You are a [xxx] legend and a [xxx] icon!',
    'You are a [xxx] rockstar and a [xxx] superstar!',
    'You are a [xxx] superhero and a [xxx] role model!',
    'You are a [xxx] king or queen and a [xxx] leader!',
    'You are a [xxx] champion and a [xxx] winner in every [xxx] way!',
    'You have the [xxx] power to overcome any [xxx] obstacle.',
    'You are [xxx] stronger than you realize.',
    'You have the [xxx] determination to [xxx] succeed.',
    'You are on the [xxx] path to greatness.',
    'You have the [xxx] courage to chase your dreams.',
    'You are [xxx] destined for greatness.',
    'You have the [xxx] ability to achieve your goals.',
    'You have the [xxx] power to make a positive impact on the world.',
    'You are [xxx] unstoppable.',
    'You are a [xxx] winner.',
    'You have the [xxx] strength to persevere through any [xxx] challenge.',
    'You are a [xxx] fighter and will not give up.',
    'You have what it takes to [xxx] succeed.',
    'You are a [xxx] leader and will inspire others.',
    'You are a [xxx] trailblazer and will pave the way for others to follow.',
    'You are a [xxx] game-changer and will make a [xxx] lasting impact.',
    'You are a [xxx] superhero and will [xxx] save the day.',
    'You are a [xxx] warrior and will conquer any [xxx] battle.',
    'You are a [xxx] champion and will [xxx] rise to the top.',
    'You are a [xxx] conqueror and will overcome any [xxx] adversity.',
    'You are a [xxx] powerhouse and will dominate your field.',
    'You are a [xxx] force to be reckoned with.',
    'You are a [xxx] trailblazer and will break new ground.',
    'You are a [xxx] leader and will guide others to success.',
    'You are a [xxx] visionary and will change the world.',
    'You are [xxx] unstoppable and will achieve your wildest dreams.',
    'You have the [xxx] potential to be anything you [xxx] want to be.',
    'You are amazing and will [xxx] accomplish great things.',
    'Believe in yourself and all that you are. Know that there is something inside you that is greater than any [xxx] obstacle.',
    'The only limits are the ones you [xxx] set for yourself.',
    "Don't let anyone [xxx] tell you that you can't achieve your goals.",
    "Don't let fear [xxx] hold you back. Take a deep breath and take the first step towards your dreams.",
    'You have the [xxx] power to create the life you want.',
    "Don't let setbacks [xxx] discourage you. Every challenge is an opportunity to grow and learn.",
    'Keep pushing [xxx] forward. You are almost there.',
    'You are capable of [xxx] overcoming any obstacle.',
    "Don't let doubt or insecurity [xxx] hold you back. Believe in yourself and your [xxx] abilities.",
    'You are capable of achieving [xxx] greatness.',
    'Your hard work and determination will [xxx] pay off.',
    "Don't let anyone else's doubts or negativity [xxx] hold you back",
];

export default hypeStatements;
