const imposterSyndromeStatements = [
    'I am qualified and capable of doing this job.',
    'My successes and achievements prove that I belong here.',
    'I have the skills and knowledge necessary to contribute to this team.',
    'I have the right to be here and to have a seat at the table.',
    "Imposter syndrome is a common feeling, and it doesn't reflect my actual abilities.",
    'I have earned my place and deserve to be here.',
    'My coworkers and superiors value my contributions and believe in my potential.',
    'I have worked hard to get to where I am and have every right to be here.',
    "It's okay to ask for help and to admit when I don't know something.",
    "I am continuously learning and growing, and that's what matters most.",
    "It's natural to feel unsure or self-doubt at times, but it's important to push through those feelings.",
    'I am capable of achieving my goals and making a positive impact.',
    'I have the support and resources I need to succeed in this role.',
    'I am confident in my abilities and know that I can handle any challenges that come my way.',
    'I am not alone in experiencing imposter syndrome, and there are ways to overcome it.',
    'I deserve to be here just as much as anyone else.',
    'I have unique strengths and experiences that add value to this team.',
    'I have overcome challenges and accomplished things in the past, and I can do it again.',
    "It's important to celebrate my achievements and recognize my own worth.",
    'I am worthy of respect and recognition for my hard work and contributions.',
    "It's okay to make mistakes, as long as I learn from them and try to do better in the future.",
    "I have a lot to offer, and I shouldn't let imposter syndrome hold me back.",
    'I am not an imposter; I am a skilled and competent professional.',
    "It's important to believe in myself and my abilities, even if I have moments of self-doubt.",
    'I have the support of my coworkers and superiors, and they believe in my potential.',
    'I have the skills and knowledge needed to succeed in this role.',
    'I have overcome challenges and achieved success in the past, and I can do it again.',
    "It's important to recognize my own worth and value.",
    'I deserve to be here and have every right to be a part of this team.',
    'I am capable of handling any challenges that come my way.',
    'I have the support and resources I need to succeed.',
    "It's okay to ask for help and admit when I don't know something.",
    'I am continuously learning and growing.',
    "It's okay to ask for help and to admit when I don't",
    "It's normal to feel like an imposter sometimes, even if you're qualified and competent.",
    "Everyone has moments of self-doubt, and it doesn't mean you're not capable.",
    'You have accomplished a lot to get to where you are today, and that is something to be proud of.',
    "Don't compare yourself to others – focus on your own achievements and progress.",
    "Remember that no one is perfect and everyone makes mistakes. It's how we learn and grow.",
    "It's okay to ask for help or clarification when needed – it shows strength, not weakness.",
    'You are your own worst critic – try to be kinder to yourself.',
    "Don't let fear hold you back – take calculated risks and learn from any setbacks.",
    'Practice self-care and prioritize your mental health.',
    'Surround yourself with supportive and positive people who believe in your abilities.',
    'Recognize and celebrate your strengths and unique skills.',
    'Remember that everyone has their own path and timeline for success.',
    "It's okay to make mistakes – they are opportunities for learning and growth.",
    "Don't let imposter syndrome define you – focus on your strengths and abilities.",
    'You are capable of achieving your goals – believe in yourself.',
    "Don't be afraid to ask for feedback and use it to improve.",
    "Don't let setbacks or failures define you – learn from them and move forward.",
    "Don't let others' perceptions of you dictate your own self-worth.",
    "You deserve to be where you are – don't let imposter syndrome hold you back.",
    'Remember that everyone has different experiences and skill sets – focus on your own unique value.',
    "Don't let perfectionism hold you back – it's okay to make mistakes and learn from them.",
    'Remember that imposter syndrome is a common and normal feeling – you are not alone.',
    "Don't be afraid to ask for support when you need it.",
    'Recognize and challenge negative thoughts and self-doubt.',
    "Don't let fear of failure hold you back – take calculated risks and learn from any setbacks.",
    'Practice gratitude and focus on the positive aspects of your life and career.',
    "Believe in your own abilities and don't let imposter syndrome hold you back.",
    "Remember that everyone has their own journey – don't compare yourself to others.",
    "Don't let others' perceptions of you affect your own self-worth.",
    "Don't be afraid to ask for help or clarification when needed.",
    'Recognize and celebrate your achievements and progress.',
    'Remember that no one is perfect and everyone makes mistakes.',
    "Believe in yourself and your abilities – don't let imposter syndrome hold you back.",
    "It's important to remember that everyone makes mistakes and no one is perfect.",
    'You are just as qualified and capable as anyone else in your field.',
    'Your accomplishments and successes are not a fluke or luck, but rather a result of your hard work and dedication.',
    "It's okay to ask for help or seek guidance when needed.",
    "It's important to recognize and acknowledge your own strengths and abilities.",
    "It's normal to feel anxious or uncertain at times, but don't let those feelings hold you back.",
    "Don't compare yourself to others or try to be someone you're not. Be true to yourself and your unique skills and abilities.",
    "It's important to remember that everyone has different experiences and backgrounds, and that diversity can be a strength.",
    "Don't be afraid to take on new challenges and try new things.",
    'Believe in yourself and your abilities.',
    "Don't let fear of failure hold you back. Embrace the opportunity to learn and grow.",
    "It's okay to make mistakes and learn from them.",
    "It's important to set realistic goals and expectations for yourself.",
    "Don't let negative thoughts or self-doubt get in the way of your success.",
    "Don't be afraid to ask for feedback or constructive criticism. It can be a valuable way to learn and improve.",
    "Remember that everyone has their own unique journey and it's okay to take your time.",
    "It's important to celebrate your successes and accomplishments, no matter how small they may seem.",
    "Don't be afraid to take risks and step outside of your comfort zone.",
    "It's important to practice self-care and prioritize your well-being.",
    "Remember that it's okay to ask for support or help when needed.",
    "Don't let setbacks or challenges discourage you. Keep a positive attitude and stay focused on your goals.",
    "It's important to be confident in your abilities and to trust yourself.",
    "Remember that it's okay to ask for clarification or more information if you're unsure about something.",
    "Don't be afraid to advocate for yourself and your needs.",
    "It's important to set boundaries and prioritize your time and energy.",
    "Don't let imposter syndrome hold you back from pursuing your dreams and goals.",
    "Remember that you are capable of achieving great things and don't let anyone else tell you otherwise.",
    "It's important to practice self-compassion and be kind to yourself.",
    "Don't let the opinions of others define your worth or value.",
    "It's important to stay true to your values and beliefs, even if they differ from those around you.",
    "Don't be afraid to ask for a promotion or raise if you feel you deserve it.",
    "Remember that it's okay to take breaks and recharge when needed.",
    "It's important to recognize and challenge negative thoughts and beliefs about yourself.",
    "Don't let imposter syndrome prevent you from speaking up and sharing your ideas.",
    'Remember that you have valuable knowledge and experience to offer.',
    "It's important to seek out mentors and supportive colleagues who can provide guidance and encouragement.",
    "Don't be afraid to ask for accommodations or support if you need it.",
    'Remember that you are capable of learning and adapting to new situations.',
    "It's important to set goals and work towards them consistently.",
    'I am qualified for my job and have worked hard to get where I am.',
    'I am capable of learning new things and improving.',
    'I have achieved successes in the past and can do so again in the future.',
    'I deserve to be here and belong just as much as anyone else.',
    'I am not expected to know everything and it is okay to ask for help.',
    'I am not alone in feeling imposter syndrome; many others experience it as well.',
    'I have a unique set of skills and experiences that add value to my team.',
    'I have accomplished things that others admire and respect.',
    'My mistakes do not define me and are opportunities for learning and growth.',
    'I have the ability to set and achieve my own goals.',
    'I am not my job title or role; I am a multifaceted individual with many strengths.',
    'I have the power to change my negative thoughts about myself.',
    'I am worthy of praise and recognition for my hard work and accomplishments.',
    'I am not a fraud and have earned my successes through my own efforts.',
    'I am capable of achieving my goals with dedication and hard work.',
    'I have the skills and abilities necessary to succeed in my field.',
    'I am confident in my abilities and know that I can contribute value.',
    'I deserve to be respected and valued for my contributions.',
    'I have the right to make mistakes and learn from them.',
    'I am not defined by my failures or setbacks.',
    'I am capable of overcoming challenges and finding solutions.',
    'I am strong and capable of handling any difficulties that may come my way.',
    'I have the power to change my circumstances and create a better future for myself.',
    'I am worthy of love and respect, regardless of my achievements or mistakes.',
    'I am not alone in my struggles and can seek support from others.',
    'I have the ability to bounce back from setbacks and move forward.',
    'I am capable of achieving my dreams with hard work and determination.',
    'I am not inferior to anyone else and am deserving of equal opportunities.',
    'I have the power to shape my own destiny and create a fulfilling life for myself.',
    'I am capable of handling difficult tasks and problem solving.',
    'I am not a failure and have many strengths and successes to be proud of.',
    'I am worthy of respect and should not compare myself negatively to others.',
    'I have the ability to overcome self-doubt and believe in myself.',
    'I am not defined by my past and have the power to create a better future.',
    'I am capable of achieving great things with perseverance and effort.',
    'I have the right to make my own choices and pursue my own goals.',
    'I am deserving of happiness and fulfillment.',
    'I am capable of creating and maintaining healthy relationships.',
    "I am not defined by others' expectations or opinions of me.",
    'I have the power to change my limiting beliefs about myself.',
    'I am worthy of love and respect, regardless of my perceived flaws or weaknesses.',
    'I am not alone in my struggles and can seek help and support from others.',
    'I am capable of learning and growing from my experiences.',
    'I have been successful in the past and can be successful again.',
    'I have received positive feedback from my peers and superiors in the past.',
    'I have been chosen for this role because of my skills and abilities.',
    'I am continuously learning and improving my skills.',
    'I have a unique perspective and valuable contributions to offer.',
    'I am deserving of my successes and accomplishments.',
    'I am not perfect and that is okay, no one is.',
    'It is natural to feel uncertain or unsure at times, but that does not mean I am not capable.',
    'I have the support of my colleagues and can ask for help when needed.',
    'I have made it this far in my career because of my hard work and dedication.',
    'I am worthy of respect and recognition for my achievements.',
    'I am not an imposter and have earned my place in this profession.',
    'I am confident in my abilities and will not let self-doubt hold me back.',
    'I am capable of handling challenges and overcoming obstacles.',
    'I have learned from my mistakes and will use them to grow and improve.',
    'I am not alone in experiencing imposter syndrome, many successful people have felt this way.',
    'I have a unique set of skills and experiences that make me valuable.',
    'I am not expected to be perfect, it is okay to make mistakes and learn from them.',
    'I have the determination and motivation to succeed.',
    'I am capable of achieving my goals and reaching new heights in my career.',
    'I am not defined by my failures, but rather by my ability to learn and grow from them.',
    'I am competent and capable of achieving success.',
    'I have the support and resources available to me to succeed.',
    'I am confident in my ability to learn and adapt to new situations.',
    'I have a strong work ethic and am dedicated to my profession.',
    'I am capable of handling new responsibilities and taking on new challenges.',
    'I am not an imposter, I have the skills and experience to succeed in this role.',
    'I am worthy of my achievements and deserve to be here.',
    'I have the capability to succeed and will not let self-doubt hold me back.',
    'I am capable and competent in my abilities.',
    'I have accomplished many things and have the skills and experience to continue doing so.',
    'I have the right to be here and belong just as much as anyone else.',
    'I am not an imposter, I have worked hard and earned my place.',
    'It is natural to feel uncertain or self-doubt at times, but I can work through those feelings.',
    'I am not alone in experiencing imposter syndrome, many successful people have felt the same way.',
    'I will not let imposter syndrome hold me back from achieving my goals.',
    'I can seek support and guidance from others to help me overcome imposter syndrome.',
    'I am capable of learning new things and improving my skills.',
    'I will not compare myself to others, but rather focus on my own progress and growth.',
    'I will practice self-compassion and speak kindly to myself.',
    'I will not let fear of failure hold me back, but rather embrace challenges as opportunities for learning and growth.',
    'I will celebrate my achievements and accomplishments, no matter how small.',
    'I will seek out opportunities for professional development and growth.',
    'I will seek out mentors and advisors who can support me in my professional journey.',
    'I will set realistic and achievable goals for myself.',
    'I will not let my own internal critic hold me back.',
    'I will seek out positive feedback and take it to heart.',
    'I will acknowledge my own strengths and capabilities.',
    'I will not let imposter syndrome dictate my actions and decisions.',
    'I will remind myself that everyone makes mistakes and that it is a natural part of learning and growth.',
    'I will focus on my own progress, rather than dwelling on past mistakes.',
    'I will practice gratitude and focus on the positive aspects of my life and career.',
    'I will take time for self-care to help manage feelings of imposter syndrome.',
    'I will seek out opportunities to share my knowledge and expertise with others.',
    'I will not let imposter syndrome define me, but rather recognize it as a common experience that I can overcome.',
    'I will take pride in my hard work and dedication to my career.',
    'I will not let imposter syndrome stand in the way of my success.',
    'I have the skills, knowledge, and determination to succeed and overcome imposter syndrome.',
    'It is normal to feel like an impostor at times, as everyone experiences self-doubt and feelings of inadequacy.',
    'Imposter syndrome is a common experience, and does not reflect your actual abilities or worth.',
    'Remember that everyone has their own unique skills and talents, and yours are just as valuable.',
    'Your accomplishments and successes are not a fluke or a result of luck, but rather a testament to your hard work and dedication.',
    'It is okay to make mistakes and not know everything. No one is perfect and we all have room to learn and grow.',
    'It is important to recognize and challenge negative or untrue thoughts about yourself.',
    'Think about all the times you have succeeded in the past and the effort and determination it took to get there.',
    'Seek out feedback from colleagues or mentors, and remember that constructive criticism is a normal and necessary part of growth and development.',
    'You do not have to prove yourself to anyone. Believe in your own abilities and worth.',
    'Remember that everyone has their own insecurities and struggles, and it is not just you.',
    'It is important to celebrate your achievements and give yourself credit where it is due.',
    'Do not compare yourself to others, as everyone is on their own unique journey and has their own set of experiences and skills.',
    'Remember that it is okay to ask for help when you need it.',
    'Focus on your strengths and the things that you are good at, rather than dwelling on your weaknesses.',
    'It is important to set realistic goals for yourself and recognize that progress takes time.',
    'Remember that success does not happen overnight, and it is important to be patient with yourself.',
    'Your worth is not determined by your job title or external markers of success.',
    'It is important to have self-compassion and be kind to yourself, rather than beating yourself up for perceived shortcomings.',
    'Remember that you are not alone in feeling like an impostor, and it is a common experience among high achievers.',
    'Focus on the things that you have control over, and try not to get too caught up in external validation or comparisons.',
    'It is important to take breaks and prioritize self-care to prevent burnout and maintain a healthy work-life balance.',
    'Remember that everyone has their own unique set of challenges and struggles, and it is okay to ask for support when needed.',
    'You are worthy and deserving of respect and recognition for your hard work and achievements.',
    'It is important to remember that setbacks and failures are a normal part of life, and it is how we handle and learn from them that matters.',
    'Try not to let imposter syndrome hold you back from pursuing opportunities or taking on new challenges.',
    'Remember that you have the skills and abilities needed to succeed, and it is important to believe in yourself.',
    'It is important to surround yourself with supportive and positive people who believe in you and your abilities.',
    'You are more capable and competent than you give yourself credit for.',
    'It is okay to ask for help or clarification when needed, as it shows that you are proactive and committed to learning and improving.',
    'Remember that everyone has their own journey and timeline for success, and it is important to focus on your own personal growth and development.',
    'I have worked hard and earned my place here.',
    'I am capable of learning and growing in this role.',
    'It is natural to feel unsure or nervous in a new environment.',
    'I am surrounded by supportive and helpful colleagues.',
    'I have been given this opportunity because I am qualified and capable.',
    'I belong here and am an important part of the team.',
    'I am not expected to be perfect and it is okay to make mistakes.',
    'I have the ability to ask for help when needed.',
    'I am confident in my abilities and am continuously improving.',
    'I have overcome challenges and obstacles in the past and can do so again.',
    'It is okay to have moments of self-doubt, but I choose to focus on my strengths.',
    'I am capable of tackling new tasks and taking on new responsibilities.',
    'I have a strong support system of friends and family who believe in me.',
    'I am constantly learning and growing in my career.',
    'I have the skills and experience necessary to excel in this role.',
    'I am capable of handling the demands of this job.',
    'I have the ability to adapt and overcome any challenges that come my way.',
    'I am confident in my decisions and actions.',
    'I am worthy of praise and recognition for my hard work.',
    'I have a positive attitude and am willing to take on new challenges.',
    'I trust in my own abilities and judgment.',
    'I am proud of my achievements and the effort I put into my work.',
    'I am capable of achieving success and making a positive impact in my field.',
    'I deserve to be here and am capable of contributing to the team.',
    'I have the support and resources necessary to succeed in this role.',
    'I am confident in my skills and abilities and am excited for the opportunities ahead.',
    'You are capable and qualified for your role.',
    'You belong in your workplace and have valuable contributions to make.',
    'Imposter syndrome is a common experience and does not reflect your actual abilities.',
    'You have achieved success in the past and can do so again.',
    'You have unique strengths and skills that make you an asset to your team.',
    'It is natural to feel uncertain or self-doubt at times, but that does not mean you are an imposter.',
    'You have earned your position through hard work and dedication.',
    'You are not alone in feeling imposter syndrome - many successful people have experienced it too.',
    'It is okay to ask for help or support when needed.',
    'You are deserving of praise and recognition for your accomplishments.',
    'You have the ability to learn and grow in your role.',
    'Your mistakes do not define you - they are opportunities for learning and growth.',
    'Your worth is not determined by your job title or salary.',
    'You have the power to change your negative thought patterns.',
    'It is important to celebrate your successes, no matter how small they may seem.',
    'You are not expected to know everything - it is okay to ask questions.',
    'You are not a fraud or an imposter - you have earned your place.',
    'It is normal to feel overwhelmed at times, but you have the skills and resources to handle it.',
    "Your worth is not based on others' opinions of you.",
    'You are capable of achieving your goals and dreams.',
    'It is important to practice self-care and prioritize your well-being.',
    'You are not alone in feeling imposter syndrome - seeking support from colleagues or a mental health professional can be helpful.',
    'Your past failures do not define your future successes.',
    'You have unique experiences and perspectives that add value to your team.',
    'It is important to challenge negative thoughts and reframe them in a more positive light.',
    'You are worthy of respect and admiration.',
    'It is okay to take credit for your hard work and accomplishments.',
    'You have the ability to overcome challenges and obstacles.',
    'Your worth is not based on your job performance or productivity.',
    'It is important to be kind to yourself and practice self-compassion.',
    'I am competent and capable of achieving my goals.',
    'I have earned my accomplishments through hard work and dedication.',
    'I am worthy of the opportunities that have been presented to me.',
    'I have the skills and abilities to succeed in my field.',
    'My successes are a result of my own abilities, not just luck or chance.',
    'I have the same right to be here and belong as anyone else.',
    'I am not an imposter, I am a qualified and competent professional.',
    'I have the right to make mistakes and learn from them, just like everyone else.',
    'I am not alone in feeling like an imposter at times, many people experience this.',
    'I am capable of seeking out help and support when needed.',
    'I can overcome imposter syndrome by recognizing and challenging negative thoughts.',
    'I am constantly learning and growing in my profession.',
    'I have the ability to ask for help and guidance when needed.',
    'I am strong enough to face my fears and doubts.',
    'I am worthy of the praise and recognition I receive.',
    'I am capable of handling challenges and setbacks.',
    'I am not defined by my mistakes or failures.',
    'I have a unique perspective and set of skills to offer.',
    'I am capable of achieving my goals and dreams.',
    'I am not alone in experiencing imposter syndrome, and seeking support can be helpful.',
    'I have the strength and resilience to overcome any obstacle.',
    'I am confident in my abilities and have earned my successes.',
    'I am capable of making a positive impact in my field.',
    'I have the right to make decisions and advocate for myself.',
    'I am worthy of love, respect, and acceptance.',
    'I am capable of achieving my full potential.',
    'I have the skills and knowledge necessary to succeed.',
    'I am not an imposter, I am a competent and qualified individual.',
    'I deserve to be successful and happy in my career.',
    'I have unique skills and perspectives to offer.',
    'I have received positive feedback and recognition for my work.',
    'I have succeeded in the past and can continue to do so.',
    'I am capable of learning and growing in my role.',
    'I am surrounded by supportive and talented colleagues.',
    'I have faced challenges and overcome them before.',
    'Imposter syndrome is a common and normal feeling, but it is not a reflection of my abilities.',
    'I have achieved my current level of success through my own efforts and merit.',
    'I am confident in my abilities and decisions.',
    'I am deserving of my accomplishments and the opportunities I have received.',
    'I am not an imposter and I belong here.',
    'I have a unique set of experiences and qualifications that make me a valuable asset.',
    'I am constantly learning and improving in my role.',
    'I am successful because of my hard work and dedication.',
    'I have received positive feedback from my colleagues and superiors.',
    'I am competent and capable of handling the tasks and responsibilities in my role.',
    'I have the skills and knowledge necessary to succeed in my career.',
    'I am confident in my ability to learn and adapt to new challenges.',
    'I am worthy of the success and opportunities that come my way.',
    'I am not alone in experiencing imposter syndrome and many others have overcome it.',
    'I have proven myself time and time again and I can continue to do so.',
    'I am capable of making valuable contributions to my team and organization.',
    'I am not an imposter, I am a qualified and talented individual.',
    'I deserve to be here and have a right to be successful.',
    'I have the skills and expertise necessary to excel in my role.',
    'I am confident in my abilities and trust in my own judgement.',
    'Everyone feels like an imposter at some point.',
    'Imposter syndrome is common, especially among high achievers.',
    "It's natural to have moments of self-doubt, but they don't define your worth.",
    'Your successes and accomplishments are proof that you belong and are qualified.',
    "It's okay to not know everything or to make mistakes.",
    'Asking for help does not make you incompetent or a fraud.',
    "It's important to remember that everyone has their own unique strengths and weaknesses.",
    'You have been given opportunities and successes for a reason.',
    'Imposter syndrome is often a result of comparing yourself to others.',
    "It's important to focus on your own progress and growth, rather than trying to be perfect.",
    'Your self-worth is not based on your job title or external validation.',
    "It's important to recognize and challenge negative self-talk.",
    "It's okay to be proud of your achievements and to own your success.",
    'Remember that everyone has their own journey and experiences.',
    "It's important to give yourself credit where credit is due.",
    "It's normal to feel like an imposter, but it doesn't make it true.",
    "You are capable and competent, even if you don't feel like it all the time.",
    "Remember that everyone makes mistakes and that it's a natural part of learning and growing.",
    "It's important to surround yourself with supportive and encouraging people.",
    "It's okay to ask for feedback and use it to improve, rather than seeing it as a personal attack.",
    'Your worth is not determined by your job or career.',
    "It's important to recognize that perfection is not attainable or necessary.",
    "It's okay to take time to care for yourself and prioritize your well-being.",
    "Remember that your worth is not based on others' opinions of you.",
    "It's important to focus on your strengths, rather than dwelling on your weaknesses.",
    "It's okay to seek out support or therapy if you're struggling with imposter syndrome.",
    'Remember that everyone has different experiences and backgrounds.',
    "It's important to set boundaries and prioritize self-care to avoid burnout.",
    'You are capable and deserving of all the opportunities and successes that come your way.',
];

export default imposterSyndromeStatements;
